[package]
name = "rust-test"
version = "0.1.0"
authors = ["Ame"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4"
png = "0.11"
indicatif = "0.13.0"